name: pipelines behave selenium

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@2

      - name: Set up Python
        uses: actions/setup-python@2
        with:
          python-version: '3.x'

      - name: Install depencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the test with behave
        uses: behave